### ISSUE TITLE
Coarse1.root type ?

### ISSUE THREAD

**Issue by luckyjim** [grand-mother/data_challenge1#2]
Hi, 

I can open Coarse1.root with different grandlib ROOT class

- EfieldRunSimdataTree
- EfieldEventSimdataTree
- EfieldEventTree

In [2]: import grand.io.root_trees as ior
In [3]: sE=ior.**EfieldEventSimdataTree**('Coarse1.root')
No valid teventefieldsimdata TTree in the file Coarse1.root. Creating a new one.

In [4]: sE
Out[4]: EfieldEventSimdataTree(_file=<cppyy.gbl.TFile object at 0x775eae0>, _file_name='Coarse1.root', _tree=<cppyy.gbl.TTree object at 0x6d16220>, _tree_name='teventefieldsimdata', _entry_list=[], _run_number=array([0], dtype=uint32), _event_number=array([0], dtype=uint32), _du_id=[], _t_0=[], _p2p=[])

In [5]: sE2=ior.**EfieldRunSimdataTree**('Coarse1.root')

In [6]: sE
Out[6]: EfieldEventSimdataTree(_file=<cppyy.gbl.TFile object at 0x775eae0>, _file_name='Coarse1.root', _tree=<cppyy.gbl.TTree object at 0x6d16220>, _tree_name='teventefieldsimdata', _entry_list=[], _run_number=array([0], dtype=uint32), _event_number=array([0], dtype=uint32), _du_id=[], _t_0=[], _p2p=[])

In [7]: sE=ior.**EfieldEventTree**('Coarse1.root')

What is the good one, please ?

**Comment by lwpiotr** [comment]
All of them are good :) If you open the ROOT file manually, and list the contents, you can see that there are 5 trees stored there:

`
[lewhoo@lwpcomp3 tmp]$ root -l Coarse1.root 
.root [0] 
Attaching file Coarse1.root as _file0...
l(TFile *) 0x3194e50
root [1] .ls
TFile**		Coarse1.root	
 TFile*		Coarse1.root	
  KEY: TTree	trun;1	trun
  KEY: TTree	teventshowersimdata;1	teventshowersimdata
  KEY: TTree	teventshowerzhaires;1	teventshowerzhaires
  KEY: TTree	trunefieldsimdata;1	trunefieldsimdata
  KEY: TTree	teventefield;1	teventefield

`

Each class of grand.io.root_trees reads/writes a different TTree:

- RunTree() will read trun
- EfieldEventTree() will read teventefield
- EfieldRunSimdataTree() will read trunefieldsimdata
- ShowerEventSimdataTree() will read teventshowersimdata
- ShowerEventZHAireSTree() will read teventshowerzhaires

**Comment by luckyjim** [comment]
ok thanks i really need to understand this ROOT data format now.
From your answer it looks like there is no such thing as a class that reads all of these TTrees at once, right?

**Comment by lwpiotr** [comment]
No, there is no such class, but it is a good idea, so I will add it.

**Comment by luckyjim** [comment]
thank you it's not blocking for me, I'll probably make a first version myself from what you do
